version: '3'
name: request-caching

services:
  request-caching-main:
    build: .
    container_name: request-caching-main
    ports:
      - "8888:8888"
    environment:
      SERVER_PORT: "8888"
    depends_on:
      - redis

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 1234
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local




