server:
  port: 8888

spring:
  redis:
    redisson:
      config: |
        singleServerConfig:
          database: 0
          address: redis://localhost:6379
          password: 1234

app:
  ttl: 10 # in minutes
